name: E2E Tests

on:
  schedule:
    - cron: "10 00 * * *"

  pull_request:
    branches:
      - master

jobs:
  E2E_WindowsEdge_Test:
    runs-on: windows-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        run: mvn -DbrowserName="Edge" -Dtest="automation.exercises.test.RegistrationTests" test

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Windows Edge Tests Report
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

      - name: Generate Allure Report Single File
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Edge_Windows_Allure_Report
          path: target/site/allure-maven-plugin/index.html

  E2E_UbuntuChrome_Test:
    runs-on: ubuntu-latest
    permissions:
        checks: write
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '21'

        - name: Set up Maven
          uses: stCarolas/setup-maven@v4.5
          with:
            maven-version: 3.9.9
        - name: Execute Tests
          run: mvn -DbrowserName="Chrome" -DheadlessExecution="true" -Dtest="${{ github.event.inputs.testsPath }}" test


        - name: Generate Allure Report Single File
          continue-on-error: true
          run: mvn allure:report

        - name: Upload Allure Report as Artifact
          uses: actions/upload-artifact@v3
          with:
            name: Chrome_Linux_Allure_Report
            path: target/site/allure-maven-plugin/index.html

        - name: Publish Report
          continue-on-error: true
          uses: dorny/test-reporter@v1
          if: success() || failure()
          with:
            name: Ubuntu Chrome Tests Report
            path: 'target/surefire-reports/TEST-*.xml'
            reporter: java-junit

